### ISSUE TITLE
Boost 1.82 has a lot of deprecations:

### ISSUE THREAD

**Issue by RandyMcMillan** [pedro-vicente/nostr_client_relay#4]
https://github.com/pedro-vicente/nostr_client_relay/blob/4bf78e92055b368c5191ede58fe398fdcde21a07/build.boost.sh#L7

I see a lot of deprecation in Boost 1.82
If there isn't a specific reason to NOT use Boost 1.84
it may be prudent to bump to Boost 1.84.

**Comment by pedro-vicente** [comment]
It seems 1.82 is the latest, released just 3 months ago?

https://www.boost.org/users/history/version_1_82_0.html

No problem in updating to 1.84, as long it does not break anything 

I did see lots of compiler warnings compiling on a Rasbberry PI, yes
